# NumPy速查代码卡片

### 1.数组创建

In [2]:
import numpy as np

# 从列表创建
a = np.array([[1, 2], [3, 4]])
print("从列表创建:\n", a)

# 全零 / 全一
zeros = np.zeros((2, 3))
ones  = np.ones((3, 2))
print("\n全零:\n", zeros)
print("全一:\n", ones)

# 等差序列
arange_arr = np.arange(0, 12, 3)      # [0, 3, 6, 9]
linspace_arr = np.linspace(0, 1, 5)   # [0., 0.25, 0.5, 0.75, 1.]
print("\narange:", arange_arr)
print("linspace:", linspace_arr)

# 随机数组
rand_arr = np.random.rand(2, 4)
print("\n随机数组:\n", rand_arr)

从列表创建:
 [[1 2]
 [3 4]]

全零:
 [[0. 0. 0.]
 [0. 0. 0.]]
全一:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

arange: [0 3 6 9]
linspace: [0.   0.25 0.5  0.75 1.  ]

随机数组:
 [[0.7608718  0.2727358  0.85578374 0.10436893]
 [0.34865259 0.14424441 0.42136373 0.95936651]]


### 2.数组属性与类型

In [3]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print("形状:", a.shape)       # (2, 3)
print("维度数:", a.ndim)      # 2
print("数据类型:", a.dtype)   # int64（默认）

# 改变数据类型
b = a.astype(np.float32)
print("转换后类型:", b.dtype)  # float32

形状: (2, 3)
维度数: 2
数据类型: int64
转换后类型: float32


### 向量化运算与广播

In [4]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

# 元素级运算
print("加法:", a + b)         # [11 22 33]
print("乘法:", a * b)         # [10 40 90]
print("幂运算:", a ** 2)      # [1 4 9]

# 广播：数组与标量
print("广播加法:", a + 5)     # [6 7 8]

# 矩阵乘法（dot product）
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("\n矩阵乘法:\n", A @ B)  # 等价于 np.dot(A, B)

加法: [11 22 33]
乘法: [10 40 90]
幂运算: [1 4 9]
广播加法: [6 7 8]

矩阵乘法:
 [[19 22]
 [43 50]]


### 5.统计聚合（含axis用法）

In [5]:
data = np.array([[1, 2, 3],
                 [4, 5, 6]])

print("全局求和:", data.sum())        # 21
print("全局均值:", data.mean())       # 3.5
print("全局最大值:", data.max())      # 6

# axis 参数：0=沿列方向（跨行），1=沿行方向（跨列）
print("每列求和:", data.sum(axis=0))  # [5 7 9]
print("每行均值:", data.mean(axis=1)) # [2. 5.]

全局求和: 21
全局均值: 3.5
全局最大值: 6
每列求和: [5 7 9]
每行均值: [2. 5.]


### 6.图像处理小实践

In [3]:
from PIL import Image
import numpy as np

# 打开
img = Image.open('C:/Users/E16/Pictures/Screenshots/屏幕截图 2025-11-09 194549.png')
arr = np.array(img)

print("图像数组形状:", arr.shape) 

# 裁剪：取中间一块
cropped = arr[100:300, 150:350]

# 上下翻转
flipped = arr[::-1, :, :]

# 提取红色通道（R）
red_channel = arr[:, :, 0]

# 保存结果
Image.fromarray(cropped).save('cropped.png')
Image.fromarray(flipped).save('flipped.png')

图像数组形状: (590, 581, 4)


### 小练习
创建一个 3×4 的全零数组

创建一个 2×5 的随机数组（均匀分布）

查看数组的 shape、dtype、size

将数组 reshape 为 4×3

In [6]:
import numpy as np
a = np.zeros ((3,4))
print(a)
b = np.random.rand (2,5)
print(b)
print('数组的shape是',a.shape,'和',b.shape)
print('数组的dtype是',a.dtype,'和',b.dtype)
print('数组的size是',a.size,'和',b.size)
aed = a.reshape(4,3)
bed = b.reshape(5,2)
print(aed,bed)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.09618555 0.63328833 0.89850462 0.02966086 0.78563149]
 [0.85542571 0.86877162 0.31240336 0.19911225 0.00932233]]
数组的shape是 (3, 4) 和 (2, 5)
数组的dtype是 float64 和 float64
数组的size是 12 和 10
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] [[0.09618555 0.63328833]
 [0.89850462 0.02966086]
 [0.78563149 0.85542571]
 [0.86877162 0.31240336]
 [0.19911225 0.00932233]]
