### numpy矩阵运算

In [4]:
import numpy as np
A =np.array([[2,1],[1,3]])
B= np.array([[1,2],[3,4]])
print(A @ B)
print(B @ A)
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
print(det_A)
print(inv_A)
b = np.array([5,6])
x = inv_A @ b
print('解x = ',x)

[[ 5  8]
 [10 14]]
[[ 4  7]
 [10 15]]
5.000000000000001
[[ 0.6 -0.2]
 [-0.2  0.4]]
解x =  [1.8 1.4]
