### 线性方程组与秩

In [15]:
#判断一个3x3矩阵是否满秩
import numpy as np
A = np.random.rand(3,3)
B = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(A)
print(B)

def full_rank(z):
    n = z.shape[0]
    rank = np.linalg.matrix_rank(z)
    return rank ==n, rank

for name,z in [('A',A),('B',B)]:
    is_full, rank = full_rank(z)
    status = '满秩'if is_full else '不满秩'
    print('{}:{} {}'.format(name,rank,status))

[[0.07205204 0.72881052 0.25509518]
 [0.05631424 0.61565033 0.04610546]
 [0.4234568  0.30786893 0.47309548]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
A:3 满秩
B:2 不满秩


#### 练习
- 1.生成一个 5×5 随机满秩矩阵 A，随机向量 b，用 solve 求 x，验证 A@x == b
- 2.生成一个欠定方程组（行<列），用 lstsq 求最小二乘解
- 3.对比 solve 和 lstsq 的适用场景

In [ ]:
import numpy as np
A1 = np.random.rand(5,5)
b1 = np.random.rand(5)
x1 = np.linalg.solve(A1,b1)
print('矩阵A1:')
print(np.round(A1,2))
print('\nb1 = {}'.format(np.round(b1,2)))
print('\n解 x1 = {}'.format(np.round(x1,2)))
result1 = A1 @ x1
if np.allclose(result1,b1):
    print('验证结果A1 @ x1 = b1 = {},完全匹配'.format(result1))
else:
    print('验证结果有误差')

矩阵A:
[[0.79 0.5  0.36 1.   0.74]
 [0.56 0.39 0.04 0.87 0.31]
 [0.92 0.51 0.6  0.26 0.04]
 [0.64 0.54 0.64 0.67 0.37]
 [0.84 0.56 0.81 0.16 0.89]]

b1 = [0.74 0.13 0.48 0.16 0.31]

解 x = [ 2.53 -6.07  1.61  1.11  0.11]
验证结果A @ x = b = [0.73679971 0.13423027 0.47562083 0.15656601 0.30551104],完全匹配


In [6]:
A2 = np.random.randn(3,5)
b2 = np.random.rand(3)
print(A2)
print(b2)
x2 = np.linalg.lstsq(A2,b2,rcond=None)
print('最小二乘解 x2 = {}'.format(x2,2))

[[-1.71114922 -0.46033312 -0.46054407 -1.28843579 -0.32567929]
 [ 1.21478959  2.18013327  0.63311655 -0.77819643  1.32493491]
 [ 0.72001142  1.962047    0.60415904 -0.7361765  -0.27103238]]
[0.31753776 0.87833265 0.41610475]
最小二乘解 x2 = (array([-0.07613886,  0.17544027, -0.00285774, -0.27826938,  0.28197854]), array([], dtype=float64), np.int32(3), array([3.77341246, 2.04189151, 1.02432968]))


3.solve和lstsq
- solve：只用于方阵且满秩，速度快，给出精确解

- lstsq：适用于任何形状矩阵，给出最小二乘意义下的最优解（即使方程组无精确解也能找到最佳近似）