# NumPy

【快速的一小时Numpy教程 - From BroCode（双语字幕）-哔哩哔哩】 https://b23.tv/kAyYcC9

前段时间我对学习的线性代数可视化和这个教程里数组维度的定义理解逻辑有“出入”，  
**为什么三维矩阵在numpy就变成了二维的？为什么线代可视化会把3×3矩阵画成三维立方体？**  
可以这样解释：  
  
**线性代数可视化展示的不是矩阵本身，而是矩阵对空间的变换效果。**  
    
  
  1. **矩阵本身（NumPy 视角）**：数字表格，ndim=2，shape=(3,3)  
  2. **矩阵的作用对象**：三维空间中的向量 (x,y,z)，需要三维坐标系  
  3. **可视化的目的**：展示变换效果，立方体是"测试图案"而非矩阵本身  


> np.array(  )里面有几层嵌套的[  ],array.ndim就是几。ndim也就是说轴  
  矩阵都是两个轴，三维矩阵的3实际上是尺寸（3行3列）  

In [40]:
import numpy as np 
import matplotlib.pyplot as plt 

#设置字体为黑体（Windows常用）或微软雅黑，以便支持中文显示

plt.rcParams['font.sans-serif'] = ['SimHei', 'Microsoft YaHei']

#解决保存图像时负号'-'显示为方块的问题

plt.rcParams['axes.unicode_minus'] = False


In [2]:
array= np.array([1,2,3,4])

print(array)

print(type(array))

print(array*2)

[1 2 3 4]
<class 'numpy.ndarray'>
[2 4 6 8]


In [3]:
#零维

array = np.array('A')

print(array.ndim)

0


In [4]:
#一维

array = np.array(['A','B','C'])  #shape=(3,)
print(array.ndim)

#二维
array = np.array([['A','B','C'],['D','E','F'],['G','H','I']]) #shape(3,3)
print(array.ndim)
arr2 = np.array([[1,2],[3,4]])#shape=(2,2)
print(arr2.ndim)

#三维
array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['A','B','C'],['D','E','F'],['G','H','I']],
                  [['A','B','C'],['D','E','F'],['G','H','I']]])#shape=(3,3,3)
print(array.ndim)

arr3 = np.array([[[1],[2]],[[3],[4]]]) #shape=(2,2,1)
print(arr3.ndim)

1
2
2
3
3


In [5]:
zeros = np.zeros((3,4))
ones = np.ones((3,3,2))
print(zeros)
print(ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [6]:
#np.full(shape, value)
full = np.full((3,),7)
print(full)

[7 7 7]


In [7]:
#等差数列 np.arange(start, stop, step)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
#均匀间隔数列 np.linspace(start, stop, num)
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
#均匀分布随机 np.random.rand(d0,d1,...)
np.random.rand(2,3)

array([[0.8885712 , 0.22553174, 0.92991716],
       [0.22421241, 0.15291314, 0.56731424]])

In [10]:
#标准正态分布 np.random.randn(d0,d1,...)
np.random.randn(3)

array([-0.97612765, -0.45106631, -1.51348542])

均匀分布的范围是固定 [0, 1),标准正态分布的范围是理论上无界，实际 ±3 以内占99.7%  
         概率是处处相等                       |中间密，两边疏  
         用途是模拟等概率事件、生成随机位置     |模拟自然误差、初始化神经网络权重  

In [11]:
#单位矩阵 np.eye(N)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#未初始化（快） np.empty(shape)
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [13]:
arr = np.empty((3, 4))
for i in range(3):
    for j in range(4):
        arr[i, j] = i * 4 + j
print(arr)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


查看数组属性

In [21]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)          
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)       

2
(2, 3)
6
int64
8
48


### 索引与切片  
基本索引  

In [ ]:
print(arr[0])           
print(arr[0][1])        
print(arr[0,1])          

[1 2 3]
2
2


切片（左闭右开）

In [18]:
print(arr[:,1:3])   # 所有行的第1~2列
print(arr[0:2,::2]) # 前两行，步长为2的列

[[2 3]
 [5 6]]
[[1 3]
 [4 6]]


布尔索引

In [27]:
mask = arr > 3
arr[mask]   #返回大于3的所有元素

array([4, 5, 6])

- 切片返回的是**视图**（修改会影响原数组）
    
- 花式索引和布尔索引返回的是**副本**
    
- 使用 `.copy()`显式复制   


### 数组操作  
改变形状  

In [61]:
arr = np.arange(12)
print(arr,'\n')
print(arr.reshape(3,4),'\n')# 返回新视图（需元素总数匹配 ，不修改原数组。但数据与原数组共享内存（即视图），修改视图中的数据会影响原数组。
print(arr.resize(3,4),'\n')       # 就地修改，元素不够时用0填充
print(arr.flatten(),'\n')         # 展平为一维（副本）
print(arr.ravel())           # 展平（视图优先）

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

None 

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [38]:
#flatten()
# 创建一个 3x4 的二维数组
arr_2d = np.arange(12).reshape(3, 4)
print("\n--- flatten 的例子 ---")
print("原始二维数组 arr_2d:\n", arr_2d)

# 使用 flatten 展平
flat_arr = arr_2d.flatten()

print("flatten 后的 flat_arr:", flat_arr)
print("flat_arr 的 shape:", flat_arr.shape)

# 关键测试：修改 flat_arr 中的元素，看原数组是否变化
flat_arr[0] = 999
print("\n修改 flat_arr[0] 为 999 后：")
print("flat_arr:", flat_arr)
print("原数组 arr_2d:\n", arr_2d,'\n\n\n\n\n')  # 原数组不变！

#ravel()
print("\n--- ravel 的例子 ---")
# 使用同一个 arr_2d
print("原始二维数组 arr_2d:\n", arr_2d)

# 使用 ravel 展平
raveled_arr = arr_2d.ravel()

print("ravel 后的 raveled_arr:", raveled_arr)
print("raveled_arr 的 shape:", raveled_arr.shape)

# 关键测试：修改 raveled_arr 中的元素，看原数组是否变化
raveled_arr[0] = 888
print("\n修改 raveled_arr[0] 为 888 后：")
print("raveled_arr:", raveled_arr)
print("原数组 arr_2d:\n", arr_2d)  # 原数组也变了！


--- flatten 的例子 ---
原始二维数组 arr_2d:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flatten 后的 flat_arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]
flat_arr 的 shape: (12,)

修改 flat_arr[0] 为 999 后：
flat_arr: [999   1   2   3   4   5   6   7   8   9  10  11]
原数组 arr_2d:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 






--- ravel 的例子 ---
原始二维数组 arr_2d:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ravel 后的 raveled_arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled_arr 的 shape: (12,)

修改 raveled_arr[0] 为 888 后：
raveled_arr: [888   1   2   3   4   5   6   7   8   9  10  11]
原数组 arr_2d:
 [[888   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


拼接与分割

In [73]:
a = np.array([[1,2,3,4,5,6,7,8,9],
              [12,23,34,45,56,67,78,89,90]])
b = np.array([[9,8,7,6,5,4,3,2,1],
              [90,98,87,76,65,54,43,32,21]])

print(np.concatenate([a,b], axis=0),'\n')   # 垂直堆叠
print(np.vstack([a,b]),'\n')                 # 同上
print(np.hstack([a,b]),'\n')                 # 水平堆叠
print(np.split(arr, 3, axis=0))         # 分成3份

[[ 1  2  3  4  5  6  7  8  9]
 [12 23 34 45 56 67 78 89 90]
 [ 9  8  7  6  5  4  3  2  1]
 [90 98 87 76 65 54 43 32 21]] 

[[ 1  2  3  4  5  6  7  8  9]
 [12 23 34 45 56 67 78 89 90]
 [ 9  8  7  6  5  4  3  2  1]
 [90 98 87 76 65 54 43 32 21]] 

[[ 1  2  3  4  5  6  7  8  9  9  8  7  6  5  4  3  2  1]
 [12 23 34 45 56 67 78 89 90 90 98 87 76 65 54 43 32 21]] 

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


转置与轴交换

In [ ]:
print(arr.T,'\n')                # 转置（仅限二维），返回视图
print(arr,'\n')
print(arr.transpose(1,0),'\n')   # 任意轴交换。新数组的轴 0 来自原数组的轴 1，新数组的轴 1 来自原数组的轴 0
print(arr.swapaxes(0,1))    # 只交换指定的两个轴，其他轴保持不变。

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] 

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### 数学运算  
算术运算（逐元素）  

In [59]:
print(a + b,'\n\n', a - b,'\n\n', a * b,'\n\n', a / b,'\n\n', a ** 2,'\n\n')
print(np.sqrt(a),'\n\n', np.sin(a),'\n\n', np.exp(a),'\n\n', np.log(a))

[[ 10  10  10  10  10  10  10  10  10]
 [102 121 121 121 121 121 121 121 111]] 

 [[ -8  -6  -4  -2   0   2   4   6   8]
 [-78 -75 -53 -31  -9  13  35  57  69]] 

 [[   9   16   21   24   25   24   21   16    9]
 [1080 2254 2958 3420 3640 3618 3354 2848 1890]] 

 [[0.11111111 0.25       0.42857143 0.66666667 1.         1.5
  2.33333333 4.         9.        ]
 [0.13333333 0.23469388 0.3908046  0.59210526 0.86153846 1.24074074
  1.81395349 2.78125    4.28571429]] 

 [[   1    4    9   16   25   36   49   64   81]
 [ 144  529 1156 2025 3136 4489 6084 7921 8100]] 


[[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
  2.64575131 2.82842712 3.        ]
 [3.46410162 4.79583152 5.83095189 6.70820393 7.48331477 8.18535277
  8.83176087 9.43398113 9.48683298]] 

 [[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
   0.6569866   0.98935825  0.41211849]
 [-0.53657292 -0.8462204   0.52908269  0.85090352 -0.521551   -0.85551998
   0.51397846  0.86006941  0.8939

聚合运算

In [65]:
print(arr.sum(),'\n',            # 总和
arr.mean(),'\n',           # 均值
arr.std(),'\n',            # 标准差
arr.min(),'\n', arr.max(),'\n',
arr.argmin(),'\n',         # 最小值的索引
arr.cumsum())        # 累加和

66 
 5.5 
 3.452052529534663 
 0 
 11 
 0 
 [ 0  1  3  6 10 15 21 28 36 45 55 66]


沿轴运算

In [67]:
print(arr.sum(axis=0),'\n',      # 沿着行方向压缩（计算每列和）
arr.mean(axis=1))     # 沿着列方向压缩（计算每行均值）

[12 15 18 21] 
 [1.5 5.5 9.5]


### 广播  
广播是NumPy中一种非常强大的机制，它允许不同形状的数组之间进行算术运算，而无需手动创建循环或复制数据。简单来说，广播会自动将较小的数组“扩展”成与较大数组兼容的形状，然后进行逐元素运算。

它的核心目的是让代码更简洁、更高效，避免写显式的循环。

#### 规则  
  两个数组从尾部开始比较维度  
  如果维度相等或其中一个为1，则兼容  
  缺失维度视为1  

In [68]:
a = np.array([[1,2,3],[4,5,6]])   # (2,3)
b = np.array([10,20,30])          # (3,) → 广播为 (1,3) → (2,3)
a + b                              # 每一行加b

array([[11, 22, 33],
       [14, 25, 36]])

In [71]:
#——>手动广播
b = b.reshape(1,3)                # 显式增加维度
#b = b[np.newaxis, :]              # 另一种方式

### 线性代数  
矩阵乘法  

In [79]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.full((3,3),9)
print(np.dot(a,b),'\n\n',
      a @ b)

[[ 54  54  54]
 [135 135 135]
 [216 216 216]] 

 [[ 54  54  54]
 [135 135 135]
 [216 216 216]]


In [83]:
A = a
print(np.linalg.inv(A),'\n\n',             # 逆矩阵
np.linalg.det(A),'\n\n',             # 行列式
np.linalg.eig(A),'\n\n',             # 特征值和特征向量
np.linalg.solve(A, b))        # 解线性方程组 Ax=b

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]] 

 -9.51619735392994e-16 

 EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -3.82264286e-16]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])) 

 [[-1. -1. -1.]
 [-7. -7. -7.]
 [ 8.  8.  8.]]


随机数  
常用分布

In [88]:
np.random.seed(42)               # 设置种子
arr = np.random.rand(3,2)              # 均匀分布 [0,1)
c = np.random.randn(100)             # 标准正态
d = np.random.randint(0,10, size=5)  # 随机整数 [0,10)
e = np.random.choice(arr.ravel(), size=3)    # 从数组中随机抽取
print (arr,'\n\n',c,'\n\n',d,'\n\n',e)

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]] 

 [ 1.57921282  0.76743473 -0.46947439  0.54256004 -0.46341769 -0.46572975
  0.24196227 -1.91328024 -1.72491783 -0.56228753 -1.01283112  0.31424733
 -0.90802408 -1.4123037   1.46564877 -0.2257763   0.0675282  -1.42474819
 -0.54438272  0.11092259 -1.15099358  0.37569802 -0.60063869 -0.29169375
 -0.60170661  1.85227818 -0.01349722 -1.05771093  0.82254491 -1.22084365
  0.2088636  -1.95967012 -1.32818605  0.19686124  0.73846658  0.17136828
 -0.11564828 -0.3011037  -1.47852199 -0.71984421 -0.46063877  1.05712223
  0.34361829 -1.76304016  0.32408397 -0.38508228 -0.676922    0.61167629
  1.03099952  0.93128012 -0.83921752 -0.30921238  0.33126343  0.97554513
 -0.47917424 -0.18565898 -1.10633497 -1.19620662  0.81252582  1.35624003
 -0.07201012  1.0035329   0.36163603 -0.64511975  0.36139561  1.53803657
 -0.03582604  1.56464366 -2.6197451   0.8219025   0.08704707 -0.29900735
  0.09176078 -1.98756891 -0.21967189  0.35711

In [92]:
print(np.random.shuffle(c),'\n\n',           # 就地打乱第一轴
np.random.permutation(e))         # 返回打乱的序列

None 

 [0.59865848 0.59865848 0.95071431]
