# 线性代数基础与NumPy

**作者**：路一瑞  
**日期**：2026-7-13到2026-8-5  
**目标**：系统学习线性代数基础理论，掌握NumPy数组操作、矩阵运算、特征值分解  
**关键库**：numpy  
**数据**：随机生成  

In [1]:
import numpy as np

## 1.数组创建与基础操作
### 1.1创建不同形状的数组

In [2]:
zeros_arr = np.zeros((3, 4))          # 全零数组
ones_arr = np.ones((2, 5))            # 全一数组
rand_arr = np.random.rand(3, 3)       # 均匀分布 [0,1) 随机数组
eye_mat = np.eye(4)                   # 单位矩阵

print("zeros (3x4):\n", zeros_arr)
print("\nones (2x5):\n", ones_arr)
print("\nrandom (3x3):\n", rand_arr)
print("\neye (4x4):\n", eye_mat)

zeros (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones (2x5):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

random (3x3):
 [[0.15606133 0.2203874  0.89546765]
 [0.63685837 0.73672659 0.97214675]
 [0.9863789  0.20790896 0.6125645 ]]

eye (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 1.2查看属性

In [ ]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print(f"形状: {arr.shape}")
print(f"数据类型: {arr.dtype}")
print(f"元素个数: {arr.size}")
print(f"维度: {arr.ndim}")

形状: (2, 3)
数据类型: int64
元素个数: 6
维度: 2


### 1.3重塑与索引

In [4]:
arr_flat = arr.flatten()
print("展平:", arr_flat)

arr_reshaped = arr.reshape(3, 2)
print("重塑为 3x2:\n", arr_reshaped)

# 索引
print("第一行第二列:", arr[0, 1])   # 输出 2
print("第二行所有列:", arr[1, :])   # 输出 [4 5 6]

展平: [1 2 3 4 5 6]
重塑为 3x2:
 [[1 2]
 [3 4]
 [5 6]]
第一行第二列: 2
第二行所有列: [4 5 6]


## 2.矩阵运算  
### 2.1 矩阵乘法

In [5]:
A = np.array([[2, 1],
              [1, 3]])
B = np.array([[1, 2],
              [3, 4]])

print("A @ B:\n", A @ B)          # 等价于 np.dot(A, B)
print("B @ A:\n", np.dot(B,A))          # 矩阵乘法不满足交换律

A @ B:
 [[ 5  8]
 [10 14]]
B @ A:
 [[ 4  7]
 [10 15]]


### 2.2行列式与逆矩阵

In [ ]:
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)

print(f"A 的行列式: {det_A:.4f}")
print("A 的逆矩阵:\n", inv_A)

# 验证 A * A_inv = I
identity_check = A @ inv_A
print("\nA * A_inv:\n", identity_check)
print("是否接近单位矩阵:", np.allclose(identity_check, np.eye(2))) #如果两个数组在容差范围内逐元素相等，则返回 True

A 的行列式: 5.0000
A 的逆矩阵:
 [[ 0.6 -0.2]
 [-0.2  0.4]]

A * A_inv:
 [[ 1.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  1.00000000e+00]]
是否接近单位矩阵: True


### 2.3解线性方程组 Ax = b

In [8]:
b = np.array([5, 6])
x = np.linalg.solve(A, b)
print("方程的解 x =", x)

# 验证 A @ x == b
print("验证 A @ x =", A @ x)

方程的解 x = [1.8 1.4]
验证 A @ x = [5. 6.]


## 3、特征值与特征向量  
### 3.1计算特征值和特征向量

特征值表示伸缩，特征向量表示不变的方向

In [9]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("特征值:", eigenvalues)
print("特征向量:\n", eigenvectors)

# 验证 Av = λv
for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]
    lam = eigenvalues[i]
    lhs = A @ v
    rhs = lam * v
    print(f"特征值 {lam:.2f}: A*v ≈ λ*v ? {np.allclose(lhs, rhs)}")

特征值: [1.38196601 3.61803399]
特征向量:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
特征值 1.38: A*v ≈ λ*v ? True
特征值 3.62: A*v ≈ λ*v ? True


### 3.2对称矩阵的特征分解（实对称矩阵特征值均为实数）

In [10]:
sym_mat = np.array([[3, 1, 0],
                    [1, 4, 2],
                    [0, 2, 5]])
eigvals_sym, eigvecs_sym = np.linalg.eigh(sym_mat)  # eigh 专门用于对称/厄米矩阵
print("对称矩阵特征值:", eigvals_sym)
print("特征向量正交性检查:\n", eigvecs_sym.T @ eigvecs_sym)  # 应为单位矩阵

对称矩阵特征值: [1.85489731 3.4760236  6.66907909]
特征向量正交性检查:
 [[ 1.00000000e+00  3.25674202e-17 -3.68116961e-17]
 [ 3.25674202e-17  1.00000000e+00  2.42916822e-17]
 [-3.68116961e-17  2.42916822e-17  1.00000000e+00]]
